// "Having X implies having Y" links for software and data/ML skills.
// Value = confidence (0-1) that a person who has used X can credibly claim Y.
// Directional: LSTM -> Deep Learning, never the reverse. Chains are multiplied (see skillgraph.js).
// Keep confidences honest: 1.0 only when X is by definition a kind of Y.
const IMPLIES = {
  // --- deep learning ---
  'LSTM': { 'Deep Learning': 1, 'Neural Networks': 1 },
  'GRU': { 'Deep Learning': 1, 'Neural Networks': 1 },
  'RNN': { 'Deep Learning': 1, 'Neural Networks': 1 },
  'CNN': { 'Deep Learning': 1, 'Neural Networks': 1, 'Computer Vision': 0.7 },
  'Autoencoders': { 'Deep Learning': 1, 'Neural Networks': 1 },
  'Encoder-Decoder': { 'Deep Learning': 0.95, 'Neural Networks': 0.95 },
  'Transformers': { 'Deep Learning': 0.95, 'NLP': 0.6 },
  'BERT': { 'NLP': 0.95, 'Deep Learning': 0.95, 'Transformers': 0.9 },
  'GPT': { 'LLMs': 0.9, 'NLP': 0.8, 'Generative AI': 0.8 },
  'GANs': { 'Deep Learning': 1, 'Neural Networks': 1, 'Generative AI': 0.95 },
  'Diffusion Models': { 'Deep Learning': 0.95, 'Generative AI': 1 },
  'Neural Networks': { 'Deep Learning': 0.85, 'Machine Learning': 1 },
  'Deep Learning': { 'Machine Learning': 1, 'Neural Networks': 0.9 },
  'TensorFlow': { 'Deep Learning': 0.85, 'Machine Learning': 0.95, 'Python': 0.85 },
  'PyTorch': { 'Deep Learning': 0.95, 'Machine Learning': 0.95, 'Python': 0.9 },
  'Keras': { 'Deep Learning': 0.9, 'Neural Networks': 0.9, 'Python': 0.85, 'TensorFlow': 0.6 },
  'Hugging Face': { 'NLP': 0.8, 'Transformers': 0.9, 'Python': 0.8 },
  // --- LLM / generative ---
  'LLMs': { 'NLP': 0.85, 'Generative AI': 0.85 },
  'LangChain': { 'LLMs': 0.9, 'Generative AI': 0.8 },
  'RAG': { 'LLMs': 0.8, 'Generative AI': 0.8, 'NLP': 0.6 },
  'Vector Databases': { 'Databases': 0.8 },
  // --- classical ML / CV / NLP ---
  'scikit-learn': { 'Machine Learning': 1, 'Python': 0.95, 'Data Analysis': 0.6 },
  'XGBoost': { 'Machine Learning': 1 },
  'Random Forest': { 'Machine Learning': 1 },
  'Reinforcement Learning': { 'Machine Learning': 0.95 },
  'Computer Vision': { 'Machine Learning': 0.7 },
  'NLP': { 'Machine Learning': 0.7 },
  'OpenCV': { 'Computer Vision': 0.95 },
  'YOLO': { 'Computer Vision': 0.95, 'Deep Learning': 0.95 },
  'Image Classification': { 'Computer Vision': 0.9, 'Machine Learning': 0.85 },
  'spaCy': { 'NLP': 0.95, 'Python': 0.9 },
  'NLTK': { 'NLP': 0.95, 'Python': 0.9 },
  'Pandas': { 'Python': 0.95, 'Data Analysis': 0.85 },
  'NumPy': { 'Python': 0.95 },
  'matplotlib': { 'Data Visualization': 0.9, 'Python': 0.9 },
  'A/B Testing': { 'Statistics': 0.7 },
  // --- MLOps ---
  'MLflow': { 'MLOps': 1, 'Machine Learning': 0.8 },
  'SageMaker': { 'MLOps': 0.85, 'Machine Learning': 0.9, 'AWS': 1 },
  'Kubeflow': { 'MLOps': 1, 'Kubernetes': 1, 'Machine Learning': 0.85 },
  // --- data engineering / BI ---
  'Spark': { 'Big Data': 0.95 },
  'Hadoop': { 'Big Data': 1 },
  'Kafka': { 'Message Queues': 0.9 },
  'RabbitMQ': { 'Message Queues': 1 },
  'Message Queues': { 'Backend Development': 0.7 },
  'Airflow': { 'Data Engineering': 0.85, 'ETL': 0.8, 'Python': 0.7 },
  'dbt': { 'ETL': 0.85, 'Data Engineering': 0.85, 'SQL': 0.95, 'Data Warehousing': 0.7 },
  'ETL': { 'Data Engineering': 0.8 },
  'Snowflake': { 'Data Warehousing': 1, 'SQL': 0.9, 'Cloud Computing': 0.7 },
  'BigQuery': { 'Data Warehousing': 1, 'SQL': 0.95, 'GCP': 1 },
  'Redshift': { 'Data Warehousing': 1, 'AWS': 1, 'SQL': 0.9 },
  'Data Warehousing': { 'Databases': 0.8, 'Data Engineering': 0.7 },
  'Tableau': { 'Data Visualization': 1, 'Business Intelligence': 1, 'Data Analysis': 0.8 },
  'Power BI': { 'Data Visualization': 1, 'Business Intelligence': 1, 'Data Analysis': 0.8 },
  'Looker': { 'Data Visualization': 1, 'Business Intelligence': 1, 'Data Analysis': 0.8 },
  'Excel': { 'Data Analysis': 0.6 },
  // --- databases ---
  'SQL': { 'Databases': 0.85 },
  'PostgreSQL': { 'SQL': 0.95, 'Databases': 1 },
  'MySQL': { 'SQL': 0.95, 'Databases': 1 },
  'SQL Server': { 'SQL': 0.95, 'Databases': 1 },
  'Oracle': { 'SQL': 0.9, 'Databases': 1 },
  'MongoDB': { 'NoSQL': 1, 'Databases': 1 },
  'Redis': { 'NoSQL': 0.8, 'Databases': 0.8 },
  'DynamoDB': { 'NoSQL': 1, 'Databases': 1, 'AWS': 1 },
  'Cassandra': { 'NoSQL': 1, 'Databases': 1 },
  'Elasticsearch': { 'Databases': 0.6, 'NoSQL': 0.6 },
  'NoSQL': { 'Databases': 1 },
  // --- frontend ---
  'React': { 'JavaScript': 0.9, 'Frontend Development': 1 },
  'Redux': { 'React': 0.85, 'JavaScript': 0.9 },
  'Next.js': { 'React': 1, 'JavaScript': 0.9, 'Frontend Development': 1 },
  'Vue': { 'JavaScript': 0.85, 'Frontend Development': 1 },
  'Nuxt': { 'Vue': 1, 'JavaScript': 0.85, 'Frontend Development': 1 },
  'Angular': { 'TypeScript': 0.9, 'JavaScript': 0.9, 'Frontend Development': 1 },
  'TypeScript': { 'JavaScript': 0.95 },
  'jQuery': { 'JavaScript': 1, 'Frontend Development': 0.8 },
  'HTML': { 'Frontend Development': 0.85 },
  'CSS': { 'Frontend Development': 0.85 },
  'Tailwind CSS': { 'CSS': 0.95, 'Frontend Development': 0.85 },
  'Bootstrap': { 'CSS': 0.9, 'Frontend Development': 0.8 },
  // --- backend ---
  'Node.js': { 'JavaScript': 0.95, 'Backend Development': 0.9 },
  'Express': { 'Node.js': 0.95, 'JavaScript': 0.9, 'Backend Development': 1, 'REST APIs': 0.7 },
  'Django': { 'Python': 1, 'Backend Development': 1, 'REST APIs': 0.6 },
  'Flask': { 'Python': 1, 'Backend Development': 1, 'REST APIs': 0.6 },
  'FastAPI': { 'Python': 1, 'Backend Development': 1, 'REST APIs': 0.8 },
  'Celery': { 'Python': 0.9, 'Backend Development': 0.8 },
  'Spring Boot': { 'Java': 1, 'Backend Development': 1, 'REST APIs': 0.6 },
  'Ruby on Rails': { 'Ruby': 1, 'Backend Development': 1 },
  'Laravel': { 'PHP': 1, 'Backend Development': 1 },
  '.NET': { 'C#': 0.9, 'Backend Development': 0.7 },
  'REST APIs': { 'Backend Development': 0.6 },
  'GraphQL': { 'Backend Development': 0.6 },
  'Microservices': { 'Backend Development': 0.8, 'System Design': 0.6 },
  // --- cloud / devops ---
  'AWS': { 'Cloud Computing': 1 },
  'Azure': { 'Cloud Computing': 1 },
  'GCP': { 'Cloud Computing': 1 },
  'AWS Lambda': { 'AWS': 1, 'Cloud Computing': 1 },
  'Amazon S3': { 'AWS': 1, 'Cloud Computing': 1 },
  'Amazon EC2': { 'AWS': 1, 'Cloud Computing': 1 },
  'Docker': { 'Containerization': 1, 'DevOps': 0.6 },
  'Kubernetes': { 'Containerization': 1, 'Docker': 0.7, 'DevOps': 0.7 },
  'Managed Kubernetes': { 'Kubernetes': 1, 'Cloud Computing': 0.8 },
  'Helm': { 'Kubernetes': 1 },
  'Terraform': { 'Infrastructure as Code': 1, 'DevOps': 0.8 },
  'Ansible': { 'Infrastructure as Code': 0.9, 'DevOps': 0.8 },
  'Jenkins': { 'CI/CD': 1, 'DevOps': 0.85 },
  'GitHub Actions': { 'CI/CD': 1, 'DevOps': 0.85 },
  'CI/CD': { 'DevOps': 0.85 },
  'Prometheus/Grafana': { 'DevOps': 0.6 },
  'Datadog': { 'DevOps': 0.6 },
  'TDD': { 'Unit Testing': 1 },

  // --- finance ---
  'Financial Modeling': { 'Financial Analysis': 0.95, 'Excel': 0.7 },
  'DCF Valuation': { 'Financial Modeling': 0.95, 'Valuation': 1, 'Financial Analysis': 0.95 },
  'Valuation': { 'Financial Analysis': 0.9 },
  'Financial Planning & Analysis': { 'Financial Analysis': 1, 'Budgeting': 0.9, 'Forecasting': 0.9, 'Financial Reporting': 0.7 },
  'Variance Analysis': { 'Financial Analysis': 0.95, 'Budgeting': 0.7 },
  'Credit Analysis': { 'Financial Analysis': 0.9, 'Risk Management': 0.75 },
  'Investment Analysis': { 'Financial Analysis': 0.95 },
  'Treasury': { 'Financial Analysis': 0.7 },
  'Financial Analysis': { 'Data Analysis': 0.6 },
  'IFRS': { 'Accounting': 0.95, 'Financial Reporting': 0.9 },
  'Financial Reporting': { 'Accounting': 0.8 },
  'Bookkeeping': { 'Accounting': 1 },
  'Accounts Payable': { 'Accounting': 0.95 },
  'Accounts Receivable': { 'Accounting': 0.95 },
  'Reconciliation': { 'Accounting': 0.9 },
  'Month-End Close': { 'Accounting': 0.95, 'Financial Reporting': 0.8, 'Reconciliation': 0.6 },
  'Cost Accounting': { 'Accounting': 1 },
  'Revenue Recognition': { 'Accounting': 0.95 },
  'Payroll': { 'Accounting': 0.6 },
  'Tax': { 'Accounting': 0.7 },
  'Auditing': { 'Accounting': 0.85, 'Internal Controls': 0.7, 'Regulatory Compliance': 0.65 },
  'Internal Controls': { 'Regulatory Compliance': 0.8, 'Risk Management': 0.8 },
  'AML/KYC': { 'Regulatory Compliance': 0.95, 'Risk Management': 0.8 },
  'QuickBooks': { 'Accounting': 0.9, 'Bookkeeping': 0.85 },
  'Xero': { 'Accounting': 0.9, 'Bookkeeping': 0.8 },
  'Sage Accounting': { 'Accounting': 0.9 },
  'NetSuite': { 'ERP': 0.95, 'Accounting': 0.8 },
  'SAP': { 'ERP': 0.95 },
  'Microsoft Dynamics': { 'ERP': 0.9 },
  'Bloomberg Terminal': { 'Financial Analysis': 0.75, 'Investment Analysis': 0.7 },
  'Pivot Tables': { 'Excel': 1, 'Data Analysis': 0.7 },
  'VLOOKUP': { 'Excel': 1 },
  'VBA': { 'Excel': 0.95 },

  // --- operations ---
  'Warehouse Management': { 'Logistics': 0.9, 'Inventory Management': 0.75, 'Operations Management': 0.8 },
  'Logistics': { 'Supply Chain Management': 0.85, 'Operations Management': 0.7 },
  'Inventory Management': { 'Supply Chain Management': 0.8, 'Operations Management': 0.7 },
  'Procurement': { 'Supply Chain Management': 0.85, 'Vendor Management': 0.7 },
  'Demand Planning': { 'Supply Chain Management': 0.9, 'Forecasting': 0.85 },
  'Production Planning': { 'Operations Management': 0.9, 'Supply Chain Management': 0.75 },
  'Supply Chain Management': { 'Operations Management': 0.7 },
  'Lean Manufacturing': { 'Process Improvement': 0.95, 'Operations Management': 0.7 },
  'Six Sigma': { 'Process Improvement': 0.95, 'Quality Management': 0.8, 'Statistics': 0.6 },
  'Process Improvement': { 'Operations Management': 0.75 },
  'Business Process Management': { 'Process Improvement': 0.65 },
  'Workforce Management': { 'Operations Management': 0.8, 'Scheduling': 0.7 },
  'Order Management': { 'Operations Management': 0.75 },
  'Project Coordination': { 'Project Management': 0.7 },
  'People Management': { 'Leadership': 0.9 },
  'Health & Safety': { 'Regulatory Compliance': 0.65 },
  'Contract Management': { 'Vendor Management': 0.6 },
};

module.exports = { IMPLIES };
