// Canonical skill -> aliases (all lowercase). Canonical name is also matched.
const SKILLS = {
  // Languages
  'JavaScript': ['javascript', 'js', 'es6', 'ecmascript'],
  'TypeScript': ['typescript'],
  'Python': ['python'],
  'Java': ['java'],
  'C++': ['c++', 'cpp'],
  'C#': ['c#', 'csharp'],
  'Go': ['golang'],
  'Rust': ['rust'],
  'Ruby': ['ruby'],
  'PHP': ['php'],
  'Swift': ['swift'],
  'Kotlin': ['kotlin'],
  'Scala': ['scala'],
  'R': ['r programming', 'rstudio'],
  'MATLAB': ['matlab'],
  'SQL': ['sql', 't-sql', 'pl/sql', 'plsql'],
  'Bash/Shell': ['bash', 'shell scripting', 'shell script'],
  'HTML': ['html', 'html5'],
  'CSS': ['css', 'css3', 'sass', 'scss', 'less'],
  // Frontend
  'React': ['react', 'react.js', 'reactjs'],
  'Angular': ['angular', 'angularjs'],
  'Vue': ['vue', 'vue.js', 'vuejs'],
  'Next.js': ['next.js', 'nextjs'],
  'Redux': ['redux'],
  'Tailwind CSS': ['tailwind', 'tailwindcss'],
  'Bootstrap': ['bootstrap'],
  'jQuery': ['jquery'],
  'Webpack': ['webpack', 'vite'],
  // Backend
  'Node.js': ['node.js', 'nodejs', 'node'],
  'Express': ['express', 'express.js', 'expressjs'],
  'Django': ['django'],
  'Flask': ['flask'],
  'FastAPI': ['fastapi'],
  'Spring Boot': ['spring boot', 'spring', 'springboot'],
  '.NET': ['.net', 'dotnet', 'asp.net'],
  'Ruby on Rails': ['rails', 'ruby on rails'],
  'Laravel': ['laravel'],
  'GraphQL': ['graphql'],
  'REST APIs': ['rest', 'restful', 'rest api', 'rest apis', 'restful api', 'restful apis'],
  'gRPC': ['grpc'],
  'Microservices': ['microservices', 'microservice'],
  // Data / DB
  'PostgreSQL': ['postgresql', 'postgres'],
  'MySQL': ['mysql'],
  'MongoDB': ['mongodb', 'mongo'],
  'Redis': ['redis'],
  'Elasticsearch': ['elasticsearch', 'elastic search'],
  'Oracle': ['oracle'],
  'SQL Server': ['sql server', 'mssql'],
  'DynamoDB': ['dynamodb'],
  'Cassandra': ['cassandra'],
  'Snowflake': ['snowflake'],
  'BigQuery': ['bigquery'],
  'Kafka': ['kafka'],
  'RabbitMQ': ['rabbitmq'],
  'Spark': ['spark', 'pyspark'],
  'Hadoop': ['hadoop'],
  'Airflow': ['airflow'],
  'ETL': ['etl', 'elt'],
  'Data Warehousing': ['data warehouse', 'data warehousing'],
  // Cloud / DevOps
  'AWS': ['aws', 'amazon web services'],
  'Azure': ['azure'],
  'GCP': ['gcp', 'google cloud'],
  'Docker': ['docker'],
  'Kubernetes': ['kubernetes', 'k8s'],
  'Terraform': ['terraform'],
  'Ansible': ['ansible'],
  'Jenkins': ['jenkins'],
  'CI/CD': ['ci/cd', 'cicd', 'continuous integration', 'continuous delivery', 'continuous deployment'],
  'GitHub Actions': ['github actions'],
  'Git': ['git', 'github', 'gitlab', 'bitbucket'],
  'Linux': ['linux', 'unix'],
  'Prometheus/Grafana': ['prometheus', 'grafana'],
  'Datadog': ['datadog'],
  // Data science / AI
  'Machine Learning': ['machine learning', 'ml'],
  'Deep Learning': ['deep learning'],
  'NLP': ['nlp', 'natural language processing'],
  'Computer Vision': ['computer vision'],
  'TensorFlow': ['tensorflow'],
  'PyTorch': ['pytorch'],
  'scikit-learn': ['scikit-learn', 'sklearn'],
  'Pandas': ['pandas'],
  'NumPy': ['numpy'],
  'LLMs': ['llm', 'llms', 'large language models', 'generative ai', 'genai'],
  'Statistics': ['statistics', 'statistical analysis', 'statistical modeling'],
  'A/B Testing': ['a/b testing', 'ab testing', 'a/b tests', 'experimentation'],
  'Data Analysis': ['data analysis', 'data analytics', 'analytics'],
  'Data Visualization': ['data visualization', 'data visualisation'],
  'Tableau': ['tableau'],
  'Power BI': ['power bi', 'powerbi'],
  'Excel': ['excel', 'microsoft excel', 'advanced excel'],
  'Looker': ['looker'],
  // Testing / practices
  'Unit Testing': ['unit testing', 'unit tests', 'jest', 'junit', 'pytest', 'mocha'],
  'Test Automation': ['test automation', 'selenium', 'cypress', 'playwright'],
  'TDD': ['tdd', 'test-driven development'],
  'Agile': ['agile'],
  'Scrum': ['scrum'],
  'Kanban': ['kanban'],
  'Jira': ['jira'],
  'DevOps': ['devops'],
  'System Design': ['system design', 'distributed systems', 'software architecture'],
  'OOP': ['oop', 'object-oriented', 'object oriented'],
  'Data Structures & Algorithms': ['data structures', 'algorithms'],
  'Security': ['cybersecurity', 'application security', 'owasp', 'infosec'],
  'OAuth/SSO': ['oauth', 'sso', 'saml', 'jwt'],
  'Mobile Development': ['android', 'ios', 'react native', 'flutter'],
  'Figma': ['figma'],
  'UI/UX': ['ui/ux', 'ux design', 'user experience', 'user interface'],
  // Business / soft
  'Project Management': ['project management', 'pmp'],
  'Product Management': ['product management', 'product roadmap', 'roadmap'],
  'Stakeholder Management': ['stakeholder management', 'stakeholders', 'stakeholder'],
  'Leadership': ['leadership', 'led a team', 'team lead', 'mentoring', 'mentorship'],
  'Communication': ['communication skills', 'communication', 'communicator'],
  'Problem Solving': ['problem solving', 'problem-solving'],
  'Collaboration': ['collaboration', 'cross-functional', 'collaborative', 'teamwork'],
  'Budgeting': ['budgeting', 'budget management', 'forecasting'],
  'Salesforce': ['salesforce'],
  'SAP': ['sap'],
  'CRM': ['crm'],
  'SEO': ['seo', 'sem'],
  'Content Marketing': ['content marketing', 'content strategy'],
  'Google Analytics': ['google analytics', 'ga4'],
  'Customer Service': ['customer service', 'customer support'],
  'Accounting': ['accounting', 'gaap', 'accounts payable', 'accounts receivable'],
  'Recruiting': ['recruiting', 'talent acquisition', 'sourcing'],
};

module.exports = { SKILLS };
