// Canonical skill -> aliases (all lowercase). Canonical name is also matched.
const SKILLS = {
  // Languages
  'JavaScript': ['javascript', 'js', 'es6', 'ecmascript'],
  'TypeScript': ['typescript'],
  'Python': ['python'],
  'Java': ['java'],
  'C++': ['c++', 'cpp'],
  'C#': ['c#', 'csharp'],
  'Go': ['golang'],
  'Rust': ['rust'],
  'Ruby': ['ruby'],
  'PHP': ['php'],
  'Swift': ['swift'],
  'Kotlin': ['kotlin'],
  'Scala': ['scala'],
  'R': ['r programming', 'rstudio'],
  'MATLAB': ['matlab'],
  'SQL': ['sql', 't-sql', 'pl/sql', 'plsql'],
  'Bash/Shell': ['bash', 'shell scripting', 'shell script'],
  'HTML': ['html', 'html5'],
  'CSS': ['css', 'css3', 'sass', 'scss', 'less'],
  // Frontend
  'React': ['react', 'react.js', 'reactjs'],
  'Angular': ['angular', 'angularjs'],
  'Vue': ['vue', 'vue.js', 'vuejs'],
  'Next.js': ['next.js', 'nextjs'],
  'Redux': ['redux'],
  'Tailwind CSS': ['tailwind', 'tailwindcss'],
  'Bootstrap': ['bootstrap'],
  'jQuery': ['jquery'],
  'Webpack': ['webpack', 'vite'],
  // Backend
  'Node.js': ['node.js', 'nodejs', 'node'],
  'Express': ['express', 'express.js', 'expressjs'],
  'Django': ['django'],
  'Flask': ['flask'],
  'FastAPI': ['fastapi'],
  'Spring Boot': ['spring boot', 'spring', 'springboot'],
  '.NET': ['.net', 'dotnet', 'asp.net'],
  'Ruby on Rails': ['rails', 'ruby on rails'],
  'Laravel': ['laravel'],
  'GraphQL': ['graphql'],
  'REST APIs': ['rest', 'restful', 'rest api', 'rest apis', 'restful api', 'restful apis'],
  'gRPC': ['grpc'],
  'Microservices': ['microservices', 'microservice'],
  // Data / DB
  'PostgreSQL': ['postgresql', 'postgres'],
  'MySQL': ['mysql'],
  'MongoDB': ['mongodb', 'mongo'],
  'Redis': ['redis'],
  'Elasticsearch': ['elasticsearch', 'elastic search'],
  'Oracle': ['oracle'],
  'SQL Server': ['sql server', 'mssql'],
  'DynamoDB': ['dynamodb'],
  'Cassandra': ['cassandra'],
  'Snowflake': ['snowflake'],
  'BigQuery': ['bigquery'],
  'Kafka': ['kafka'],
  'RabbitMQ': ['rabbitmq'],
  'Spark': ['spark', 'pyspark'],
  'Hadoop': ['hadoop'],
  'Airflow': ['airflow'],
  'ETL': ['etl', 'elt'],
  'Data Warehousing': ['data warehouse', 'data warehousing'],
  // Cloud / DevOps
  'AWS': ['aws', 'amazon web services'],
  'Azure': ['azure'],
  'GCP': ['gcp', 'google cloud'],
  'Docker': ['docker'],
  'Kubernetes': ['kubernetes', 'k8s'],
  'Terraform': ['terraform'],
  'Ansible': ['ansible'],
  'Jenkins': ['jenkins'],
  'CI/CD': ['ci/cd', 'cicd', 'continuous integration', 'continuous delivery', 'continuous deployment'],
  'GitHub Actions': ['github actions'],
  'Git': ['git', 'github', 'gitlab', 'bitbucket'],
  'Linux': ['linux', 'unix'],
  'Prometheus/Grafana': ['prometheus', 'grafana'],
  'Datadog': ['datadog'],
  // Data science / AI
  'Machine Learning': ['machine learning', 'ml'],
  'Deep Learning': ['deep learning'],
  'NLP': ['nlp', 'natural language processing'],
  'Computer Vision': ['computer vision'],
  'TensorFlow': ['tensorflow'],
  'PyTorch': ['pytorch'],
  'scikit-learn': ['scikit-learn', 'sklearn'],
  'Pandas': ['pandas'],
  'NumPy': ['numpy'],
  'LLMs': ['llm', 'llms', 'large language models'],
  'Statistics': ['statistics', 'statistical analysis', 'statistical modeling'],
  'A/B Testing': ['a/b testing', 'ab testing', 'a/b tests', 'experimentation'],
  'Data Analysis': ['data analysis', 'data analytics', 'analytics'],
  'Data Visualization': ['data visualization', 'data visualisation'],
  'Tableau': ['tableau'],
  'Power BI': ['power bi', 'powerbi'],
  'Excel': ['excel', 'microsoft excel', 'advanced excel'],
  'Looker': ['looker'],
  // Testing / practices
  'Unit Testing': ['unit testing', 'unit tests', 'jest', 'junit', 'pytest', 'mocha'],
  'Test Automation': ['test automation', 'selenium', 'cypress', 'playwright'],
  'TDD': ['tdd', 'test-driven development'],
  'Agile': ['agile'],
  'Scrum': ['scrum'],
  'Kanban': ['kanban'],
  'Jira': ['jira'],
  'DevOps': ['devops'],
  'System Design': ['system design', 'distributed systems', 'software architecture'],
  'OOP': ['oop', 'object-oriented', 'object oriented'],
  'Data Structures & Algorithms': ['data structures', 'algorithms'],
  'Security': ['cybersecurity', 'application security', 'owasp', 'infosec'],
  'OAuth/SSO': ['oauth', 'sso', 'saml', 'jwt'],
  'Mobile Development': ['android', 'ios', 'react native', 'flutter'],
  'Figma': ['figma'],
  'UI/UX': ['ui/ux', 'ux design', 'user experience', 'user interface'],
  // Business / soft
  'Project Management': ['project management', 'pmp'],
  'Product Management': ['product management', 'product roadmap', 'roadmap'],
  'Stakeholder Management': ['stakeholder management', 'stakeholders', 'stakeholder'],
  'Leadership': ['leadership', 'led a team', 'team lead', 'mentoring', 'mentorship'],
  'Communication': ['communication skills', 'communication', 'communicator'],
  'Problem Solving': ['problem solving', 'problem-solving'],
  'Collaboration': ['collaboration', 'cross-functional', 'collaborative', 'teamwork'],
  'Budgeting': ['budgeting', 'budget management', 'budget planning', 'annual budget'],
  'Salesforce': ['salesforce'],
  'SAP': ['sap'],
  'CRM': ['crm'],
  'SEO': ['seo', 'sem'],
  'Content Marketing': ['content marketing', 'content strategy'],
  'Google Analytics': ['google analytics', 'ga4'],
  'Customer Service': ['customer service', 'customer support'],
  'Accounting': ['accounting', 'gaap'],
  'Recruiting': ['recruiting', 'talent acquisition', 'sourcing'],
};


// Software + data/ML extensions: concept nodes (what job descriptions ask for) and
// specific tools/techniques (what resumes mention). Links between them live in implications.js.
Object.assign(SKILLS, {
  // concepts
  'Neural Networks': ['neural networks', 'neural network', 'neural nets'],
  'Generative AI': ['generative ai', 'genai', 'gen ai'],
  'Reinforcement Learning': ['reinforcement learning'],
  'Time Series Analysis': ['time series', 'time-series'],
  'Feature Engineering': ['feature engineering'],
  'Recommender Systems': ['recommender systems', 'recommendation systems', 'recommendation engine'],
  'MLOps': ['mlops', 'ml ops', 'model deployment'],
  'Big Data': ['big data'],
  'Data Engineering': ['data engineering', 'data pipelines', 'data pipeline'],
  'Business Intelligence': ['business intelligence'],
  'Cloud Computing': ['cloud computing', 'cloud platforms', 'cloud infrastructure'],
  'Containerization': ['containerization', 'containerisation', 'containers'],
  'Infrastructure as Code': ['infrastructure as code', 'iac'],
  'Frontend Development': ['frontend development', 'front-end development', 'frontend', 'front-end', 'front end'],
  'Backend Development': ['backend development', 'back-end development', 'backend', 'back-end', 'back end'],
  'Databases': ['databases', 'database'],
  'NoSQL': ['nosql'],
  'Message Queues': ['message queue', 'message queues', 'event streaming', 'pub/sub'],
  // deep learning techniques
  'LSTM': ['lstm', 'long short-term memory', 'long short term memory'],
  'GRU': ['gru'],
  'RNN': ['rnn', 'recurrent neural network', 'recurrent neural networks'],
  'CNN': ['cnn', 'cnns', 'convolutional neural network', 'convolutional neural networks'],
  'Autoencoders': ['autoencoder', 'autoencoders', 'auto-encoder', 'variational autoencoder', 'vae'],
  'Encoder-Decoder': ['encoder-decoder', 'encoder decoder', 'seq2seq', 'sequence-to-sequence'],
  'Transformers': ['transformer', 'transformers', 'attention mechanism', 'self-attention'],
  'BERT': ['bert', 'roberta', 'distilbert'],
  'GPT': ['gpt', 'gpt-4', 'chatgpt', 'openai api'],
  'GANs': ['gan', 'gans', 'generative adversarial'],
  'Diffusion Models': ['diffusion models', 'stable diffusion'],
  'Keras': ['keras'],
  'Hugging Face': ['hugging face', 'huggingface'],
  'LangChain': ['langchain', 'llamaindex'],
  'RAG': ['rag', 'retrieval-augmented generation', 'retrieval augmented generation'],
  'Vector Databases': ['vector database', 'vector databases', 'pinecone', 'faiss', 'chroma'],
  // classical ML / CV / NLP tooling
  'XGBoost': ['xgboost', 'lightgbm', 'catboost'],
  'Random Forest': ['random forest', 'decision trees', 'gradient boosting'],
  'OpenCV': ['opencv'],
  'YOLO': ['yolo'],
  'Image Classification': ['image classification', 'object detection', 'image segmentation'],
  'spaCy': ['spacy'],
  'NLTK': ['nltk'],
  'matplotlib': ['matplotlib', 'seaborn'],
  // MLOps / data engineering
  'MLflow': ['mlflow'],
  'SageMaker': ['sagemaker'],
  'Kubeflow': ['kubeflow'],
  'dbt': ['dbt'],
  'Redshift': ['redshift'],
  // cloud / devops / backend
  'AWS Lambda': ['aws lambda'],
  'Amazon S3': ['amazon s3', 's3'],
  'Amazon EC2': ['ec2'],
  'Managed Kubernetes': ['eks', 'gke', 'aks'],
  'Helm': ['helm'],
  'Celery': ['celery'],
  'Nuxt': ['nuxt'],
});


// Finance and operations: concept nodes (what job descriptions ask for) and the specific work/tools that prove them.
// Links between them live in implications.js.
Object.assign(SKILLS, {
  // --- finance: concepts ---
  'Financial Analysis': ['financial analysis', 'financial analytics', 'financial insight'],
  'Financial Modeling': ['financial modeling', 'financial modelling', 'financial models', 'three-statement model', '3-statement model'],
  'Financial Reporting': ['financial reporting', 'financial statements', 'management accounts', 'management reporting', 'profit and loss', 'p&l', 'balance sheet', 'balance sheets', 'income statement', 'cash flow statement'],
  'Financial Planning & Analysis': ['fp&a', 'fpa', 'financial planning and analysis', 'financial planning & analysis'],
  'Forecasting': ['forecasting', 'financial forecasting', 'revenue forecasting', 'sales forecasting', 'demand forecasting'],
  'Valuation': ['valuation', 'company valuation', 'comparable company analysis'],
  'Investment Analysis': ['investment analysis', 'equity research', 'portfolio management', 'portfolio analysis', 'asset management'],
  'Risk Management': ['risk management', 'risk assessment', 'risk assessments', 'credit risk', 'market risk', 'operational risk'],
  'Regulatory Compliance': ['regulatory compliance', 'compliance', 'regulatory reporting'],
  'Internal Controls': ['internal controls', 'internal control', 'sox', 'sarbanes-oxley'],
  // --- finance: specific work and tools ---
  'DCF Valuation': ['dcf', 'discounted cash flow'],
  'Variance Analysis': ['variance analysis', 'budget variance', 'variance reporting'],
  'Credit Analysis': ['credit analysis', 'credit underwriting', 'credit assessment'],
  'Treasury': ['treasury', 'cash management', 'liquidity management', 'cash flow management'],
  'Auditing': ['audit', 'audits', 'auditing', 'internal audit', 'external audit', 'statutory audit'],
  'IFRS': ['ifrs'],
  'Bookkeeping': ['bookkeeping', 'general ledger', 'journal entries', 'ledger'],
  'Accounts Payable': ['accounts payable', 'ap processing', 'supplier invoices', 'invoice processing'],
  'Accounts Receivable': ['accounts receivable', 'ar processing', 'credit control'],
  'Reconciliation': ['reconciliation', 'reconciliations', 'bank reconciliation', 'account reconciliation'],
  'Month-End Close': ['month-end close', 'month end close', 'month-end', 'period-end close', 'financial close', 'year-end close'],
  'Cost Accounting': ['cost accounting', 'standard costing', 'activity-based costing', 'cost analysis'],
  'Revenue Recognition': ['revenue recognition', 'asc 606', 'ifrs 15'],
  'Payroll': ['payroll'],
  'Tax': ['tax', 'taxation', 'tax compliance', 'tax returns', 'vat'],
  'AML/KYC': ['aml', 'kyc', 'anti-money laundering', 'know your customer', 'financial crime'],
  'QuickBooks': ['quickbooks', 'quick books'],
  'Xero': ['xero'],
  'Sage Accounting': ['sage 50', 'sage 200', 'sage intacct', 'sage accounting'],
  'NetSuite': ['netsuite'],
  'Bloomberg Terminal': ['bloomberg', 'bloomberg terminal'],
  'Pivot Tables': ['pivot table', 'pivot tables'],
  'VLOOKUP': ['vlookup', 'xlookup', 'index match'],
  'VBA': ['vba', 'excel macros'],
  // --- operations: concepts ---
  'Operations Management': ['operations management', 'operational management', 'daily operations', 'operational excellence', 'operations planning'],
  'Supply Chain Management': ['supply chain', 'supply chain management', 'supply-chain'],
  'Logistics': ['logistics', 'freight', 'freight forwarding', 'transportation management', 'distribution centre', 'distribution center', 'shipping and receiving', 'fleet management'],
  'Process Improvement': ['process improvement', 'continuous improvement', 'process optimization', 'process optimisation', 'kaizen', 'operational efficiency', 'workflow optimization'],
  'Quality Management': ['quality management', 'quality control', 'quality systems', 'iso 9001', 'qms'],
  'Procurement': ['procurement', 'purchasing', 'strategic sourcing', 'vendor sourcing'],
  'Vendor Management': ['vendor management', 'supplier management', 'supplier relationship management', 'vendor relations'],
  'ERP': ['erp', 'enterprise resource planning'],
  // --- operations: specific work and methods ---
  'Inventory Management': ['inventory management', 'inventory control', 'stock control', 'stock management', 'inventory planning', 'cycle counts', 'cycle counting'],
  'Warehouse Management': ['warehouse management', 'warehouse operations', 'wms', 'warehousing'],
  'Demand Planning': ['demand planning', 's&op', 'sales and operations planning'],
  'Production Planning': ['production planning', 'production scheduling', 'master scheduling', 'mrp'],
  'Lean Manufacturing': ['lean manufacturing', 'lean methodology', 'lean principles', 'lean six sigma', '5s', 'value stream mapping'],
  'Six Sigma': ['six sigma', '6 sigma', 'lean six sigma', 'green belt', 'black belt', 'dmaic'],
  'Business Process Management': ['business process', 'business process management', 'process mapping', 'process documentation', 'standard operating procedures', 'sops'],
  'Workforce Management': ['workforce management', 'staff scheduling', 'headcount planning', 'workforce planning'],
  'Scheduling': ['scheduling', 'shift scheduling', 'rostering', 'resource scheduling'],
  'Order Management': ['order management', 'order processing', 'order fulfilment', 'order fulfillment'],
  'Project Coordination': ['project coordination', 'programme coordination', 'program coordination', 'project scheduling'],
  'People Management': ['people management', 'line management', 'team management', 'staff management', 'supervised a team', 'supervised staff', 'supervising staff', 'supervising a team', 'shift supervisor', 'team supervisor'],
  'Contract Management': ['contract management', 'contract administration', 'contract negotiation'],
  'Health & Safety': ['health and safety', 'health & safety', 'ehs', 'hse', 'osha', 'nebosh'],
  'Microsoft Dynamics': ['microsoft dynamics', 'dynamics 365', 'd365'],
});

module.exports = { SKILLS };
